version: '3.8'

services:
  mysqldb:
    image: sqlmetal
    restart: always
    ports:
      - "3306:3306"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    networks:
      - metalnet

  eureka-server:
    image: sbeureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      retries: 5
    networks:
      - metalnet

  metal:
    image: sbmetal
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysqldb:
        condition: service_healthy
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/metal?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    networks:
      - metalnet
      
  api-gateway:
    image: sbapig
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES[0].id=metalrate
      - SPRING_CLOUD_GATEWAY_ROUTES[0].uri=http://metal:8082/
      - SPRING_CLOUD_GATEWAY_ROUTES[0].predicates[0]=Path=/metal-exchange/**
      - SPRING_CLOUD_GATEWAY_ROUTES[1].id=currencyxchng
      - SPRING_CLOUD_GATEWAY_ROUTES[1].uri=http://currency:8081/
      - SPRING_CLOUD_GATEWAY_ROUTES[1].predicates[0]=Path=/currency-exchange/**
      - SPRING_CLOUD_GATEWAY_ROUTES[2].id=main
      - SPRING_CLOUD_GATEWAY_ROUTES[2].uri=http://mainrun:8080/
      - SPRING_CLOUD_GATEWAY_ROUTES[2].predicates[0]=Path=/sell/**
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - metalnet

  currency:
    image: sbcurrx
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - metalnet
    
  mainrun:
    image: sbmainrun
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - metalnet

networks:
  metalnet:
    driver: bridge
