apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tombstone2k/sbapig
          ports:
            - containerPort: 8888
          # env:
          #   - name: eureka.client.service-url.defaultZone
          #     value: http://eureka-server-service:8761/eureka
          #   - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
          #     value: currency-deployment
          #   - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
          #     value: http://currency-service:8081/
          #   - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
          #     value: "Path=/currency-exchange/**"
          env:
            - name: eureka.client.service-url.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eurekaURL

          envFrom:
              # This might contain environment-wide settings. Like the domain name that your application uses or a production only feature flag.
            - configMapRef:
                name: api-gateway-config

          
