apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  selector:
    app: currency
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - name: currency
          image: tombstone2k/sbcurrx
          ports:
            - containerPort: 8081
          env:
            - name: eureka.client.service-url.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eurekaURL
          # env:
          #   - name: eureka.client.service-url.defaultZone
          #     value: http://eureka-server-service:8761/eureka
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
