apiVersion: v1
kind: Service
metadata:
  name: metal-service
spec:
  selector:
    app: metal
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metal
  template:
    metadata:
      labels:
        app: metal
    spec:
      containers:
        - name: metal
          image: tombstone2k/sbmetal
          ports:
            - containerPort: 8082
          env:
            - name: eureka.client.service-url.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eurekaURL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysqldb-service:3306/metal?allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            # - name: SPRING_JPA_DATABASE_PLATFORM
            #   value: "org.hibernate.dialect.MySQLDialect"
            # - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            #   value: "update"
            # - name: SPRING_JPA_SHOW_SQL
            #   value: "true"
          envFrom: 
            - configMapRef:
                name: jpa-config
          # readinessProbe:
          #   exec:
          #     command:
          #       - "sh"
          #       - "-c"
          #       - "mysql -h mysqldb-service -u admin -p password -e 'SELECT 1;'"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
